# Generated by Django 5.2.8 on 2025-11-14 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('persona_contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('licencia', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('certificacion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('horas_vuelo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_transporte', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aéreo')], max_length=10)),
                ('distancia_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_carga', models.CharField(max_length=50)),
                ('peso_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('volumen_m3', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas_especiales', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('tipo_aeronave', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('piloto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('año', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('conductor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('tipo_seguro', models.CharField(max_length=50)),
                ('aseguradora', models.CharField(max_length=100)),
                ('cobertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.aeronave')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.aeronave')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.carga')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.piloto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo')),
            ],
        ),
    ]
