# Generated by Django 4.2.7 on 2025-11-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_cliente_apellido_cliente_nombre_cliente_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('CONDUCTOR', 'Conductor'), ('PILOTO', 'Piloto')], default='CLIENTE', max_length=10),
        ),
    ]
