# Generated by Django 4.2.7 on 2025-11-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='conductor_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='transporte.conductor'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='piloto_asignado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='transporte.piloto'),
        ),
    ]
